name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  release:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm exec rust-just build
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
          generate_release_notes: true
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
  publish:
    needs: [release, tests]
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: ./.github/workflows/publish.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
