name: release

on: 
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  publish-precheck:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: "latest"
        - name: Install dependencies
          run: npm ci
        - name: npm check
          run: npm publish --dry-run
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        - name: jsr check
          run: npx jsr publish --dry-run

  release:
    needs: [publish-precheck, tests]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm exec rust-just build

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'dist/**/*'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
          generate_release_notes: true
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
  publish:
    needs: [release, publish-precheck]
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: ./.github/workflows/publish.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
