name: tests

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - run: npm ci
      - run: npm exec rust-just build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 1

  node:
    needs: build
    name: Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22, "latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - run: npm ci
      - run: npm exec rust-just test-node

  deno:
    needs: build
    name: Deno ${{ matrix.deno }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ["v1.x", "v2.x", "latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - run: npm exec rust-just test-deno

  bun:
    needs: build
    name: Bun ${{ matrix.bun }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun: ["latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun }}
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - run: npm exec rust-just test-bun

      - name: Update Coverage Badge
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main
